#!/usr/bin/env php
<?php

set_time_limit(0);

$app = require_once __DIR__. '../../bootstrap.php';

use Classes\Console\ConsoleCommand;

$application = $app['console'];
$application->add(new ConsoleCommand);
$application->run();

?>
